### ISSUE TITLE
Adicionar uma pequena descrição nas indicações

### ISSUE THREAD

**Issue by rochabianca** [devMozao/estante#1]
Olá, vi seu projeto e achei excelente e deveras interessante!

Uma coisa que eu acho que ajudaria também é colocar uma pequena descrição do livro ou o porquê ele seria uma boa indicação, um ponto que você achou interessante (só um desses, acho, senão ficaria muito texto por indicação), o que acha?

E mais uma vez, que projeto top!

**Comment by kaiofelipejs** [comment]
+1

**Comment by devmozao** [comment]
Olá @rochabianca , tudo bem?

Ontem pensei exatamente sobre isso: em colocar uma descrição do pq o livro é bom. Porém me deparei com o seguinte desafio: o layout do documento. E aí pensei em duas formas:

1- Criar um documento à parte e colocar um link no título para redirecionar neste doc. Ficaria assim:

[**O Poder do Hábito**](https://google.com) | *Power of Habits*
autor: Charles Duhigg
pre-req: nenhum
tags: soft skill 

2 - Colocar uma pequena descrição abaixo das tags, com a descrição do livro. Ficaria assim:

**O Poder do Hábito** | *Power of Habits* 
autor: Charles Duhigg 
pre-req: nenhum 
tags: soft skill 
desc: o livro apresenta, a partir da análise cientifica da psicologia, os comportamentos de indivíduos, organizações e sociedades e o pq eles acontecem. A partir da análise, utilizando de uma excelente didática com exemplos do mundo real, ele prova que é possível mudar os seus próprios hábitos e comportamentos, tanto para o indivíduo quanto para uma organização ou sociedade a partir da análise comportamental.  (e ai adicionar uma tag de "must read" tambem, nao sei).

O que vc acha? 
(@kaiofelipejs pode contribuir tb).

Queria também encontrar uma maneira de destacar um livro do outro, com um fundo cinza e fundo branco, como se fosse um grid. Acho que ajudaria no visual, pra identificar onde acaba a info de um livro, e onde começa a outra.

Talvez usar alguma badge, também auxiliaria a dar destaques especificos pra cada livro. Preciso testar com calma.

EDIT: talvez adicionar a capa do livro também, não sei. Daqui a pouco eu to fazendo uma frontpage completa. HAHAHAHA

**Comment by kaiofelipejs** [comment]
Acho mais prático (não sei se é a palavra certa) a opção 2. Algo onde a pessoa bata o olho, escaneie e veja se é isso que busca. Essa descrição geralmente existe já quando estamos no e-commerce vendo o livro, então basicamente é um CTRL C + CTRL V da pessoa autora do PR. 

A ideia de destacar com fundo cinza e branco é boa, principalmente se adotarmos a opção 2 onde terá mais texto. 

A capa acho que não precisa não. Assim já eliminamos o viés de julgar o livro pela capa também ahahahah.

**Comment by rochabianca** [comment]
Também gosto da opção 2, uma vez que a info já fica ali ao bater o olho, como o @kaiofelipejs falou. Quanto ao fundo branco, bom..... da pra botar uma pequena marcação, acho

> Tipo assim, se os comentários no github pegarem MD

``` assim também é uma opção ```

da pra ver alguns exemplos em sites de markdown online (exemplo: https://stackedit.io/app#), o que vocês acham?

**Comment by devmozao** [comment]
Bom dia turma! Vamos la:

1. Vou testar algumas mudanças hoje no visual, tentando aplicar a opção 2.
2. Tenho mais livros pra adicionar na lista também. 
3. Além do design, vou criar um roadmap pra mapear as mudanças a serem feitas no projeto, e aí vou atuando conforme o planejamento.
4. Mais pra frente, vou fazer uma SPA open source com todos os livros e integrar a este projeto também. 

É bom pq quero praticar um pouco o ciclo de integração contínua com uma SPA responsiva (vue.js), microsserviços (node.js) e banco de dados em mongoDB/firebase.

Enfim: vou subir as alterações agora, e aí vcs vão avaliando se ficou bom ou não, pf. =)

**Comment by devmozao** [comment]
@rochabianca nossa, ficou MUITO MELHOR com o jeito que vc organizou. Eu nem tinha entendido que poderia ser feito desse jeito! 

Obrigado! =)

**Comment by rochabianca** [comment]
brigadinha :DD

**Comment by kaiofelipejs** [comment]
Ficou muito bom!!! 👏

**Comment by mechamogeo** [comment]
I will work on this enchancement and i will too make my parcel making a website in the future and add some books and e-books, please keep the semantic of the data to website work well in the future 😸 

@devMozao just modifying the issue, creating a template to help!

**Comment by devmozao** [comment]
Sinopses added by @geovanipfranca on pull request **237eb90**
