### ISSUE TITLE
Livro incrível sobre OKR's

### ISSUE THREAD

**Issue by mechamogeo** [devMozao/estante#10]
**Avalie o que Importa** | *Measure What Matters*
*Como o Google, Bono Vox e a Fundação Gates Sacudiram o Mundo com os OKRs*

O lendário capitalista de risco, John Doerr, revela como o sistema de Objetivos e Resultados-chaves (OKRs) ajudou gigantes da tecnologia, como Intel e Google, a alcançarem um crescimento exponencial ― e como ele pode ajudar qualquer organização a prosperar.
```
autor: John Doerr
pre-req: nenhum
tags: okrs, lean, soft skill
dica: @geovanipfranca 
```

**Comment by mechamogeo** [comment]
A metodologia é relativamente fácil de entender e aplicar. Uma leitura extraordinária (simples e objetiva), uma abordagem espetacular (sempre no foco). :book:

**Comment by devmozao** [comment]
Merge realizado no PR https://github.com/devMozao/estante/pull/13
