### ISSUE TITLE
Outro livro muito bom

### ISSUE THREAD

**Issue by mechamogeo** [devMozao/estante#11]
**O poder do tempo livre**
*Descubra seu potencial, crie projetos paralelos e torne sua vida mais incrível*

Você quer mudar sua vida, mas não tem tempo. Bobagem. Todo mundo tem tempo. Confie em mim. A ideia deste livro é que você encontre tempo onde acha que ele não existe. Que você descubra o que realmente gosta de fazer, para criar um projeto paralelo ou aperfeiçoar o que você já faz. Este livro não é simplesmente para ser lido. É para ser usado. Então faça bom uso dele. Comece agora mesmo a se dedicar àquilo que você ama. Isso vai fazer uma grande diferença na sua felicidade. Escolha viver uma vida incrível. Ela é muito curta para não ser.
```
autor: Luciano Braga
pre-req: nenhum
tags: time management
dica: @geovanipfranca 
```

**Comment by mechamogeo** [comment]
Não é um livro pesado de ser lido, mas pode pegar desprevenido aquele que julga pela capa ou sinopse. é um livro que nos convida a pensar e olhar pra dentro, relembrar os tempos de infancia de um modo a entender e responder a seguinte pergunta "onde estão aquela criatividade e vontade mesmo de fazer algo"?

**Comment by devmozao** [comment]
Livro adicionado no PR https://github.com/devMozao/estante/pull/13
