### ISSUE TITLE
Mais um vai :D

### ISSUE THREAD

**Issue by mechamogeo** [devMozao/estante#12]
**Trilogia da Fundação**

A humanidade está em risco. Uma ciência revolucionária prevê uma longa e inevitável era de trevas e barbárie. Para evitar que isso aconteça, o chamado plano Seldon é colocado em prática ao longo de séculos, e percorre a história da galáxia, prevendo conflitos de nossa civilização. Mas poderá o comportamento humano obedecer a um padrão científico?
```
autor: Isaac Asimov
pre-req: nenhum
tags: ficção ciêntifica
dica: @geovanipfranca 
```

**Comment by mechamogeo** [comment]
Esse livro é impressionante, recebeu o prêmio Hugo de Melhor série de ficção científica e fantasia de todos os tempos e foi baseado no livro clássico "Declínio e queda do Império Romano" do escritor Edward Gibbon.

**Comment by devmozao** [comment]
Livro adicionado no PR https://github.com/devMozao/estante/pull/13
