### ISSUE TITLE
Indicação de Livro

### ISSUE THREAD

**Issue by throberto** [devMozao/estante#14]
**Arquitetura Limpa** | *Clean Architecture: A Craftsman's Guide to Software Structure and Design*

As regras universais de arquitetura de software aumentam dramaticamente a produtividade dos desenvolvedores ao longo da vida dos sistemas de software.

```
autor: Robert Cecil Martin
pre-req: nenhum
tags: tags clean code, clean architecture
dica: @throberto
```

**Comment by throberto** [comment]
Cuidado com a versão em português, assim como o "Código Limpo" a tradução desse livro acaba tendo alguns problemas (palavras fora de contexto por exemplo).

**Comment by cssorlandi** [comment]
Esse livro é realmente muito bom 💙

**Comment by devmozao** [comment]
book added. ♥
