### ISSUE TITLE
Indicação de livro - :book: The Pragmatic Programmer

### ISSUE THREAD

**Issue by cssorlandi** [devMozao/estante#15]
**O Programador Pragmático: De Aprendiz a Mestre** | *The Pragmatic Programmer: your journey to mastery*

O Programador Pragmático ilustra as melhores práticas e as principais armadilhas do desenvolvimento de software. Destinado a todos envolvidos com programação, de codificadores iniciantes a programadores experientes e gerentes responsáveis por projetos de software, apresenta lições simples que promovem rápidas melhorias na produtividade pessoal, precisão e satisfação profissional.
```
autor: Andrew Hunt e David Thomas
pre-req: nenhum
tags: personal management, developer, soft skill
dica: @csorlandi
```

**Comment by devmozao** [comment]
Livro add. ♥
