### ISSUE TITLE
Indicação de livro - :book: Refatoração: Aperfeiçoando o Design de Códigos Existentes

### ISSUE THREAD

**Issue by cssorlandi** [devMozao/estante#16]
**Refatoração: Aperfeiçoando o Design de Códigos Existentes** | *Refactoring: Improving the Design of Existing Code*

Por mais de vinte anos, programadores experientes no mundo inteiro contaram com o livro Refatoração de Martin Fowler para aperfeiçoar o design de códigos existentes e melhorar a manutenibilidade do software, assim como para deixar o código existente mais fácil de entender. Refatoração 2ª edição contém um catálogo atualizado das refatorações e inclui exemplos de código JavaScript bem como novos exemplos funcionais que demonstram a refatoração sem classes.
```
autor: Martin Fowler
pre-req: clean code, ddd, clean architecture
tags: developer, refactoring, architecture
dica: @csorlandi
```

**Comment by devmozao** [comment]
Livro add. ♥
