### ISSUE TITLE
Indicação de livro - :book: Algoritmos E Lógica da Programação

### ISSUE THREAD

**Issue by ThiagoCrepequer** [devMozao/estante#17]
**Algoritmos E Lógica Da Programação** 

Com linguagem simples e didática – sem, no entanto, fugir da complexidade do assunto –, o livro procura tornar prática a lógica de programação, além de mostrar aos estudantes um caminho mais adequado na construção dos algoritmos. O desenvolvimento do raciocínio lógico e da abstração de procedimentos e dados são as maiores dificuldades para os estudantes dos cursos introdutórios. Nesse sentido, os autores resolvem os problemas propostos passo a passo, apresentando todos os conceitos envolvidos por meio de fluxogramas e em conjunto com pseudocódigos.
```
autor: Marcelo A. Furlan de Souza; Marcelo Marques Gomes; Marcio Vieira Soares
pre-req: nenhum
tags: lógica de programação
dica: @ThiagoCrepequer
```

**Comment by devmozao** [comment]
Book added. ♥
