### ISSUE TITLE
Design Patterns: Elements of Reusable Object-Oriented Software

### ISSUE THREAD

**Issue by g-nogara** [devMozao/estante#18]
**Padrões de Projeto** | *Design Patterns*
*Elements of Reusable Object-Oriented Software*

Livro fundamental para arquitetos de software, os 23 padrões descritos aqui tornaram-se mundialmente famosos e reconhecidos pela sua eficiência e elegância. Um verdadeiro best-seller mundial.
```
autor: Erich Gamma, John Vlissides, Richard Helm, Ralph Johnson
pre-req: nenhum
tags: Design Patterns, Código limpo, Engenharia de software
dica: @g-nogara
```

**Comment by devmozao** [comment]
Book added. ♥
