### ISSUE TITLE
99 Bottles of OOP - 2nd Edition

### ISSUE THREAD

**Issue by iagocavalcante** [devMozao/estante#19]
**99 Bottles of OOP - 2nd Edition** | *99 Bottles of OOP - 2nd Edition*

O livro aborda vários tópicos como: 

* Reconhecer quando o código é "bom o suficiente"
* Obtendo o melhor valor do Desenvolvimento Orientado a Testes (TDD)
* Fazendo refatoração adequada, não "rehacktoring" aleatório
* Localizando conceitos enterrados no código
* Encontrar nomes que transmitam um significado mais profundo
* Alterar o código com segurança seguindo as "Regras de Flocagem"
* Simplificando novas adições com o princípio aberto / fechado
* Evitando condicionais obedecendo ao Princípio de Substituição de Liskov
* Fazendo melhorias direcionadas, reduzindo os odores de código
* Melhorando a mutabilidade com polimorfismo
* Fabricação de objetos de simulação usando fábricas
* Protegendo-se contra a incerteza ao afrouxar o acoplamento
* Desenvolvendo uma estética de programação 
```
autor: Sandi Metz
pre-req: Conhecer sobre lógica de programação e já conhecer linguagem que você vai querer o livro (PHP, Ruby ou JS)
tags: OOP, Design de Software
dica: @iagocavalcante
```

**Comment by devmozao** [comment]
Livro adicionado. Obrigado pela contribuição! ♥
