### ISSUE TITLE
Indicação de livro - Code Complete Um Guia Pratico P/ Construcao

### ISSUE THREAD

**Issue by iagocavalcante** [devMozao/estante#20]
**Code Complete: Um Guia Prático P/ Construção** | *Code Complete: Practical Handbook of Software Construction*

> Faça uma abordagem estratégica à construção de software - e produza produtos superiores - com esta edição totalmente atualizada do guia premiado e elogiado de Steve McConnell para as melhores práticas de desenvolvimento de software. 

Com esse `abstract` o livro aborda realmente práticas escelentes pra quem tem interesse em seguir na área, ele alcança todos os níveis, um livro realmente excelente.
```
autor: Steve McConnell
pre-req: Nenhum
tags: Conceitos de Software
dica: @iagocavalcante
```

**Comment by devmozao** [comment]
Livro adicionado. Obrigado pela contribuição! ♥
